import { INestApplication } from '@nestjs/common';
import { OpenAPIObject } from '@nestjs/swagger';
import { Test, TestingModule } from '@nestjs/testing';
import request from 'supertest';
import { App } from 'supertest/types';

import { AppModule } from '../src/app.module';
import { ERROR_CODES } from '../src/common/constants/error-codes.constants';
import { ApiErrorResponse } from '../src/common/interfaces/api-response.interface';
import { API_BASE_PATH } from '../src/config/api.constants';
import { configureApp } from '../src/config/app.setup';
import { API_TAG, API_TAGS } from '../src/config/swagger-tags';
import {
  SWAGGER_DOCS_ROUTE,
  SWAGGER_ENABLED_KEY,
  SWAGGER_JSON_ROUTE,
} from '../src/config/swagger.config';
import { BEARER_AUTH_NAME, setupSwagger } from '../src/config/swagger.setup';
import { AuthService } from '../src/modules/auth/auth.service';
import { TestAuthentication } from '../src/modules/auth/testing/authentication.testing';

/**
 * The API's own documentation, end to end.
 *
 * **Everything here is answered without touching the database**, which is what
 * lets the suite run with no PostgreSQL at all — the same constraint
 * `app.e2e-spec.ts` works under, and for the same reason. The document is
 * generated by inspecting the application's metadata, and the two documentation
 * routes are served by `SwaggerModule` from memory.
 *
 * The suite boots **two** applications, because the whole point of the env gate
 * is that it has two states and a test proving one of them proves nothing about
 * the other. `docsOn` is the developer machine; `docsOff` is the production
 * default.
 */
const auth = new TestAuthentication();

/**
 * Boots an application configured exactly as `main.ts` configures one:
 * `configureApp` first, then `setupSwagger`, then `init`. Whether the
 * documentation is actually mounted is `SWAGGER_ENABLED`, which each suite sets
 * before it calls this.
 */
async function bootApplication(): Promise<INestApplication<App>> {
  const moduleRef: TestingModule = await Test.createTestingModule({
    imports: [AppModule],
  })
    .overrideProvider(AuthService)
    .useValue(auth.stub)
    .compile();

  const app: INestApplication<App> = moduleRef.createNestApplication();

  configureApp(app);
  setupSwagger(app);
  await app.init();

  return app;
}

describe('API documentation (e2e)', () => {
  let app: INestApplication<App>;
  let document: OpenAPIObject;

  beforeAll(async () => {
    // Set before the module is compiled: @nestjs/config reads process.env, and
    // an explicit `true` is what makes this suite independent of NODE_ENV.
    process.env[SWAGGER_ENABLED_KEY] = 'true';

    app = await bootApplication();

    const response = await request(app.getHttpServer()).get(SWAGGER_JSON_ROUTE);

    document = response.body as OpenAPIObject;
  });

  afterAll(async () => {
    delete process.env[SWAGGER_ENABLED_KEY];
    await app.close();
  });

  /** Every operation in the document, flattened, since most assertions want it. */
  const operations = () =>
    Object.entries(document.paths).flatMap(([path, item]) =>
      Object.entries(item as Record<string, Record<string, unknown>>)
        .filter(([method]) =>
          ['get', 'post', 'put', 'patch', 'delete'].includes(method),
        )
        .map(([method, operation]) => ({ path, method, operation })),
    );

  // ---------------------------------------------------------------------------
  // The two endpoints
  // ---------------------------------------------------------------------------

  describe('the endpoints', () => {
    it('serves a valid OpenAPI document as JSON', async () => {
      const response = await request(app.getHttpServer())
        .get(SWAGGER_JSON_ROUTE)
        .expect(200)
        .expect('Content-Type', /application\/json/);

      const body = response.body as OpenAPIObject;

      expect(body.openapi).toMatch(/^3\./);
      expect(body.info.title).toBe('CRM TimeSheet API');
      expect(body.info.version).toBeTruthy();
      // 75 paths carrying 124 operations across the 28 controllers.
      expect(Object.keys(body.paths).length).toBeGreaterThan(70);
    });

    it('serves the interactive UI as HTML', async () => {
      const response = await request(app.getHttpServer())
        .get(SWAGGER_DOCS_ROUTE)
        .expect(200)
        .expect('Content-Type', /text\/html/);

      expect(response.text).toContain('<div id="swagger-ui">');
    });

    /**
     * The UI is served from `swagger-ui-dist` inside this process. If these
     * assets were missing the page would render blank, which is the failure
     * this asserts against rather than the HTML alone.
     */
    it('serves the UI’s own scripts from this origin', async () => {
      await request(app.getHttpServer())
        .get(`${SWAGGER_DOCS_ROUTE}/swagger-ui-init.js`)
        .expect(200);

      await request(app.getHttpServer())
        .get(`${SWAGGER_DOCS_ROUTE}/swagger-ui-bundle.js`)
        .expect(200);
    });

    /**
     * The documentation routes are registered straight onto the Express
     * adapter, outside Nest's routing pipeline — so no guard runs and the raw
     * body is not wrapped in the Feature 006 envelope. Both halves are asserted
     * because both surprise a reader: the docs are reachable with no token (they
     * have to be — they are what tells a caller how to get one), and a client
     * reading `docs-json` must not look for `data`.
     */
    it('is reachable without an access token and is not enveloped', async () => {
      const response = await request(app.getHttpServer())
        .get(SWAGGER_JSON_ROUTE)
        .expect(200);

      const body = response.body as Record<string, unknown>;

      expect(body.success).toBeUndefined();
      expect(body.data).toBeUndefined();
      expect(body.openapi).toBeDefined();
    });
  });

  // ---------------------------------------------------------------------------
  // The paths are the real ones
  // ---------------------------------------------------------------------------

  describe('the documented paths', () => {
    /**
     * The single most valuable property here: the document is generated from
     * the configured application, so the global prefix and the URI version are
     * in every path and "Try it out" hits the route the reader is looking at.
     * Generated before `configureApp`, every path would be missing `/api/v1`
     * and every request from the page would 404.
     */
    it('carries the global prefix and the version on every path', () => {
      const paths = Object.keys(document.paths);

      expect(paths.length).toBeGreaterThan(0);

      for (const path of paths) {
        expect(
          path.startsWith(`${API_BASE_PATH}/`) || path === API_BASE_PATH,
        ).toBe(true);
      }
    });

    /** A representative route from each of the larger modules. */
    it.each([
      ['get', `${API_BASE_PATH}/departments`],
      ['post', `${API_BASE_PATH}/departments`],
      ['get', `${API_BASE_PATH}/departments/{id}`],
      ['post', `${API_BASE_PATH}/auth/login`],
      ['post', `${API_BASE_PATH}/auth/refresh`],
      ['get', `${API_BASE_PATH}/employees`],
      ['get', `${API_BASE_PATH}/projects/{projectId}/members`],
      ['get', `${API_BASE_PATH}/employees/{employeeId}/projects`],
      ['get', `${API_BASE_PATH}/public-holidays/calendar/{year}/{month}`],
      ['get', `${API_BASE_PATH}/me/leave-requests`],
      ['patch', `${API_BASE_PATH}/leave-requests/{id}/status`],
      ['get', `${API_BASE_PATH}/timesheets/me`],
      ['post', `${API_BASE_PATH}/timesheets/{id}/approve`],
      ['post', `${API_BASE_PATH}/reports/{reportType}/export`],
      ['get', `${API_BASE_PATH}/permissions/me/effective`],
      ['put', `${API_BASE_PATH}/users/{id}/permissions`],
      ['get', `${API_BASE_PATH}/work-schedule`],
      ['get', `${API_BASE_PATH}/email/health`],
      ['get', `${API_BASE_PATH}/health`],
    ])('documents %s %s', (method, path) => {
      expect(document.paths[path]).toBeDefined();
      expect(
        (document.paths[path] as Record<string, unknown>)[method],
      ).toBeDefined();
    });

    it('documents every controller in the application', () => {
      // 28 controllers, and none of them contributes zero routes.
      expect(operations().length).toBeGreaterThanOrEqual(120);
    });

    it('gives every operation a summary and a success response', () => {
      for (const { path, method, operation } of operations()) {
        const responses = operation.responses as Record<string, unknown>;

        expect(operation.summary).toEqual(expect.any(String));
        expect(
          `${method} ${path}: ${JSON.stringify(Object.keys(responses))}`,
        ).toMatch(/20[01]/);
      }
    });
  });

  // ---------------------------------------------------------------------------
  // Tags
  // ---------------------------------------------------------------------------

  describe('the tags', () => {
    it('declares every tag with a description, in reading order', () => {
      expect(document.tags?.map((tag) => tag.name)).toEqual(
        API_TAGS.map((tag) => tag.name),
      );

      for (const tag of document.tags ?? []) {
        expect(tag.description).toEqual(expect.any(String));
      }
    });

    /**
     * Both directions, because each catches a different rot: a tag used but not
     * declared is a typo that quietly creates a group of one, and a tag
     * declared but not used is a heading for a module that no longer exists.
     */
    it('uses exactly the tags it declares', () => {
      const declared: string[] = API_TAGS.map((tag) => tag.name);
      const used = [
        ...new Set(
          operations().flatMap(
            ({ operation }) => (operation.tags as string[] | undefined) ?? [],
          ),
        ),
      ];

      expect(used.filter((tag) => !declared.includes(tag))).toEqual([]);
      expect(declared.filter((tag) => !used.includes(tag))).toEqual([]);
    });

    /** Two controllers, one domain — the reader should not have to know that. */
    it('groups the two halves of a shared domain under one tag', () => {
      const tagsOf = (path: string, method: string) =>
        (document.paths[path] as Record<string, Record<string, unknown>>)[
          method
        ].tags as string[];

      expect(tagsOf(`${API_BASE_PATH}/leave-requests`, 'get')).toEqual([
        API_TAG.LeaveRequests,
      ]);
      expect(tagsOf(`${API_BASE_PATH}/me/leave-requests`, 'get')).toEqual([
        API_TAG.LeaveRequests,
      ]);
    });
  });

  // ---------------------------------------------------------------------------
  // Authentication
  // ---------------------------------------------------------------------------

  describe('authentication', () => {
    it('declares the bearer scheme the Authorize button uses', () => {
      expect(document.components?.securitySchemes?.[BEARER_AUTH_NAME]).toEqual(
        expect.objectContaining({
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        }),
      );
    });

    /**
     * The global `JwtAuthGuard` makes "protected" the default for every route
     * in this application, and the documentation has to say the same thing or a
     * consumer will write a client that omits the header.
     */
    it('requires the bearer token on every route but the public ones', () => {
      const withoutSecurity = operations()
        .filter(({ operation }) => operation.security === undefined)
        .map(({ method, path }) => `${method} ${path}`);

      expect(withoutSecurity.sort()).toEqual(
        [
          `get ${API_BASE_PATH}`,
          `get ${API_BASE_PATH}/health`,
          `post ${API_BASE_PATH}/auth/activate`,
          `post ${API_BASE_PATH}/auth/forgot-password`,
          `post ${API_BASE_PATH}/auth/login`,
          `post ${API_BASE_PATH}/auth/refresh`,
          `post ${API_BASE_PATH}/auth/reset-password`,
        ].sort(),
      );
    });

    /**
     * **The subtle one.** `POST /auth/login` and `POST /auth/refresh` genuinely
     * answer `401`, and it means something completely different there: the
     * credential in the *body* was refused, not that a token was missing.
     * Reusing the guard's wording would have told a reader that login needs a
     * token in order to issue one — so the two are the only public routes that
     * document a `401`, and the description they carry says so.
     */
    it('describes a 401 on a public route as a refused credential', () => {
      const publicOperations = operations().filter(
        ({ operation }) => operation.security === undefined,
      );

      const withUnauthorized = publicOperations
        .filter(({ operation }) =>
          Object.keys(operation.responses as Record<string, unknown>).includes(
            '401',
          ),
        )
        .map(({ method, path }) => `${method} ${path}`);

      expect(withUnauthorized.sort()).toEqual([
        `post ${API_BASE_PATH}/auth/login`,
        `post ${API_BASE_PATH}/auth/refresh`,
      ]);

      for (const { operation } of publicOperations) {
        const unauthorized = (operation.responses as Record<string, unknown>)[
          '401'
        ] as { description?: string } | undefined;

        if (unauthorized) {
          expect(unauthorized.description).toContain(
            'there is no access token involved on a public route',
          );
        }
      }
    });

    /** …and every guarded route documents both refusals it can produce. */
    it('documents 401 on every guarded route', () => {
      for (const { method, path, operation } of operations().filter(
        ({ operation: op }) => op.security !== undefined,
      )) {
        expect(`${method} ${path}`).toBeTruthy();
        expect(
          Object.keys(operation.responses as Record<string, unknown>),
        ).toContain('401');
      }
    });

    it('documents 403 on the permission-gated routes', () => {
      for (const [path, method] of [
        [`${API_BASE_PATH}/timesheets/{id}/approve`, 'post'],
        [`${API_BASE_PATH}/users/{id}/permissions`, 'put'],
        [`${API_BASE_PATH}/permissions`, 'get'],
        [`${API_BASE_PATH}/reports`, 'get'],
        [`${API_BASE_PATH}/users`, 'get'],
      ] as const) {
        const operation = (
          document.paths[path] as Record<string, Record<string, unknown>>
        )[method];

        expect(
          Object.keys(operation.responses as Record<string, unknown>),
        ).toContain('403');
      }
    });
  });

  // ---------------------------------------------------------------------------
  // The error envelope (Feature 033)
  // ---------------------------------------------------------------------------

  describe('the error envelope', () => {
    it('is a named schema rather than an inline shape', () => {
      const envelope = document.components?.schemas?.ErrorEnvelope as
        | { properties?: Record<string, unknown>; required?: string[] }
        | undefined;

      expect(envelope).toBeDefined();
      expect(Object.keys(envelope?.properties ?? {}).sort()).toEqual([
        'errorCode',
        'message',
        'params',
        'path',
        'statusCode',
        'success',
        'timestamp',
      ]);
    });

    /**
     * `errorCode` and `params` are absent rather than null when an exception
     * carries no code — the contract Feature 033 gave clients to branch on.
     */
    it('marks errorCode and params optional', () => {
      const envelope = document.components?.schemas?.ErrorEnvelope as {
        required?: string[];
      };

      expect(envelope.required).toContain('success');
      expect(envelope.required).toContain('statusCode');
      expect(envelope.required).not.toContain('errorCode');
      expect(envelope.required).not.toContain('params');
    });

    /**
     * The reason the reusable decorator exists: every failure on every route
     * points at the one schema, so none of the ~500 documented error responses
     * can describe the envelope slightly differently.
     */
    it('is what every documented failure refers to', () => {
      const failures = operations().flatMap(({ method, path, operation }) =>
        Object.entries(operation.responses as Record<string, unknown>)
          .filter(([status]) => Number(status) >= 400)
          .map(([status, response]) => ({
            where: `${method} ${path} ${status}`,
            response: response as {
              content?: Record<string, { schema?: { $ref?: string } }>;
            },
          })),
      );

      expect(failures.length).toBeGreaterThan(300);

      for (const { where, response } of failures) {
        expect(
          `${where} -> ${response.content?.['application/json']?.schema?.$ref}`,
        ).toContain('#/components/schemas/ErrorEnvelope');
      }
    });

    /** The three every authenticated route carries, whatever else it does. */
    it('attaches 429 and 500 to every route', () => {
      for (const { method, path, operation } of operations()) {
        const statuses = Object.keys(
          operation.responses as Record<string, unknown>,
        );

        expect(`${method} ${path}: ${statuses.join(',')}`).toContain('429');
        expect(`${method} ${path}: ${statuses.join(',')}`).toContain('500');
      }
    });

    /** A client that retries into a limiter extends the block. */
    it('documents Retry-After on the 429', () => {
      const operation = (
        document.paths[`${API_BASE_PATH}/departments`] as Record<
          string,
          Record<string, unknown>
        >
      ).get;
      const rateLimited = (operation.responses as Record<string, unknown>)[
        '429'
      ] as { headers?: Record<string, unknown> };

      expect(rateLimited.headers?.['Retry-After']).toBeDefined();
    });
  });

  // ---------------------------------------------------------------------------
  // The per-status error examples
  // ---------------------------------------------------------------------------

  /**
   * **What a reader actually sees under each failure**, as opposed to which
   * schema it points at — which the block above already asserts.
   *
   * The schema alone is not enough, and the reason is worth stating: a response
   * carrying nothing but the `$ref` leaves Swagger UI to assemble an example
   * from the *field-level* `example:` values on `ErrorEnvelope`, and those
   * belong to different failures. The result was one body — a `404` status
   * beside an authentication code beside permission `params` — rendered
   * identically under the `401`, the `403`, the `429` and the `500` of every
   * route in the API. It was internally impossible and it made two statuses
   * look like the same response.
   *
   * These assertions are document-wide rather than spot-checks on one route,
   * because the examples come from one map and a spot-check would pass while
   * some other status quietly rendered the wrong body.
   */
  describe('the per-status error examples', () => {
    /** Every documented failure, with whatever example bodies it renders. */
    const errorResponses = () =>
      operations().flatMap(({ method, path, operation }) =>
        Object.entries(operation.responses as Record<string, unknown>)
          .filter(([status]) => Number(status) >= 400)
          .map(([status, response]) => {
            const media = (
              response as {
                content?: Record<
                  string,
                  {
                    example?: ApiErrorResponse;
                    examples?: Record<string, { value?: ApiErrorResponse }>;
                  }
                >;
              }
            ).content?.['application/json'];

            const values =
              media?.example !== undefined
                ? [media.example]
                : Object.values(media?.examples ?? {}).flatMap(
                    ({ value }) => value ?? [],
                  );

            return { where: `${method} ${path} ${status}`, status, values };
          }),
      );

    /** Every example body in the document, flattened. */
    const examples = (status?: number) =>
      errorResponses()
        .filter(
          (response) => status === undefined || +response.status === status,
        )
        .flatMap(({ where, values }) =>
          values.map((value) => ({ where, value })),
        );

    it('renders an example under every documented failure', () => {
      const withoutOne = errorResponses()
        .filter(({ values }) => values.length === 0)
        .map(({ where }) => where);

      expect(withoutOne).toEqual([]);
    });

    /**
     * **The property the whole change exists for.** No example may claim a
     * status other than the one it hangs under.
     */
    it('gives every example the status code of the response it sits under', () => {
      for (const { where, value } of examples()) {
        expect(`${where} -> ${value.statusCode}`).toBe(
          `${where} -> ${where.split(' ').pop()}`,
        );
        expect(value.success).toBe(false);
        expect(value.path).toEqual(expect.any(String));
        expect(value.timestamp).toEqual(expect.any(String));
      }
    });

    /** An invented code would be one a frontend could never key a translation on. */
    it('uses only codes the catalog defines', () => {
      const known: string[] = Object.values(ERROR_CODES);

      for (const { where, value } of examples()) {
        if (value.errorCode !== undefined) {
          expect(`${where} -> ${value.errorCode}`).toBe(
            `${where} -> ${known.find((code) => code === value.errorCode)}`,
          );
        }
      }
    });

    /** `params` never travel alone — they are values a coded message interpolates. */
    it('never shows params without a code', () => {
      for (const { where, value } of examples()) {
        expect(`${where} -> ${JSON.stringify(value.params)}`).toBe(
          value.params === undefined || value.errorCode !== undefined
            ? `${where} -> ${JSON.stringify(value.params)}`
            : `${where} -> undefined`,
        );
      }
    });

    /**
     * **The most visibly wrong part of what this replaced.** Nothing in this
     * application throws a coded not-found, so a `404` is the envelope's
     * documented "key absent entirely" case — and the old example put
     * `AUTH_UNAUTHENTICATED` and permission `params` on one.
     */
    it('shows a 404 with no code and no params', () => {
      const found = examples(404);

      expect(found.length).toBeGreaterThan(0);

      for (const { where, value } of found) {
        expect(`${where} -> ${value.errorCode}`).toBe(`${where} -> undefined`);
        expect(`${where} -> ${value.params}`).toBe(`${where} -> undefined`);
      }
    });

    /**
     * The two refusals a guarded route can answer `401` with, and a client's
     * response to them is opposite: `AUTH_UNAUTHENTICATED` says refresh and then
     * show the login screen, `AUTH_INACTIVE_USER` says do neither, because
     * signing in again fails forever. `findActiveUser` gives both branches the
     * same message on purpose, so the code is the only thing that separates
     * them — which is exactly why both have to be shown.
     */
    it('shows both guarded 401 codes on every protected route', () => {
      const guarded = operations().filter(
        ({ operation }) => operation.security !== undefined,
      );

      expect(guarded.length).toBeGreaterThan(100);

      for (const { method, path, operation } of guarded) {
        const media = (
          (operation.responses as Record<string, unknown>)['401'] as {
            content: Record<
              string,
              { examples: Record<string, { value: ApiErrorResponse }> }
            >;
          }
        ).content['application/json'];

        const codes = Object.values(media.examples).map(
          ({ value }) => value.errorCode,
        );

        expect(`${method} ${path} -> ${codes.sort().join()}`).toBe(
          `${method} ${path} -> ${[
            ERROR_CODES.AUTH_UNAUTHENTICATED,
            ERROR_CODES.AUTH_INACTIVE_USER,
          ]
            .sort()
            .join()}`,
        );
      }
    });

    /**
     * **The drift this caught.** `AUTH_INACTIVE_USER` was described as a `403`
     * for as long as the descriptions existed, and `auth.service.ts` has only
     * ever thrown it from `findActiveUser` as an `UnauthorizedException`. The
     * assertion is document-wide and in both directions, so neither the example
     * nor a future description can put it back under the wrong status.
     */
    it('never shows AUTH_INACTIVE_USER anywhere but a 401', () => {
      const statuses = errorResponses()
        .filter(({ values }) =>
          values.some(
            ({ errorCode }) => errorCode === ERROR_CODES.AUTH_INACTIVE_USER,
          ),
        )
        .map(({ status }) => status);

      expect(statuses.length).toBeGreaterThan(100);
      expect([...new Set(statuses)]).toEqual(['401']);
    });

    /**
     * **The `@Public()` half.** `POST /auth/login` and `POST /auth/refresh` are
     * the only public routes that answer `401`, and there it means the
     * credential in the *body* was refused. Showing the guard's code would have
     * contradicted the description printed directly above it.
     */
    it('shows a refused credential on a public 401', () => {
      const codes = operations()
        .filter(({ operation }) => operation.security === undefined)
        .flatMap(({ operation }) => {
          const media = (
            (operation.responses as Record<string, unknown>)['401'] as
              | {
                  content: Record<
                    string,
                    { examples: Record<string, { value: ApiErrorResponse }> }
                  >;
                }
              | undefined
          )?.content['application/json'];

          return Object.values(media?.examples ?? {}).map(
            ({ value }) => value.errorCode,
          );
        });

      expect([...new Set(codes)].sort()).toEqual(
        [
          ERROR_CODES.AUTH_INVALID_CREDENTIALS,
          ERROR_CODES.AUTH_REFRESH_TOKEN_INVALID,
          ERROR_CODES.AUTH_REFRESH_TOKEN_REUSED,
        ].sort(),
      );
    });

    /**
     * `403`'s three causes are not interchangeable: one is fixed by granting a
     * permission, one cannot be fixed at all, and one is about the account
     * having no employment record behind it. All three are shown, and only the
     * permission one carries the `params` its code documents.
     */
    it('shows all three kinds of 403, with params only on the permission one', () => {
      const codes = examples(403).map(({ value }) => value.errorCode);

      expect(codes).toContain(ERROR_CODES.AUTHORIZATION_PERMISSION_DENIED);
      expect(codes).toContain(ERROR_CODES.AUTHORIZATION_ACCOUNT_ADMIN_REQUIRED);
      expect(codes).toContain(ERROR_CODES.AUTH_NO_EMPLOYEE_RECORD);

      for (const { where, value } of examples(403)) {
        const expected =
          value.errorCode === ERROR_CODES.AUTHORIZATION_PERMISSION_DENIED
            ? {
                requiredPermissions: expect.any(String) as unknown as string,
                mode: expect.any(String) as unknown as string,
              }
            : undefined;

        expect({ where, params: value.params }).toEqual({
          where,
          params: expected,
        });
      }
    });

    it.each([
      [429, ERROR_CODES.RATE_LIMIT_EXCEEDED],
      [500, ERROR_CODES.INTERNAL_ERROR],
    ])('shows %s as %s', (status, code) => {
      const found = examples(status);

      expect(found.length).toBeGreaterThan(0);

      for (const { where, value } of found) {
        expect(`${where} -> ${value.errorCode}`).toBe(`${where} -> ${code}`);
      }
    });

    /**
     * `400` is not only the `ValidationPipe`'s, and the description has always
     * said so — a domain rule may answer in the same shape with its own code.
     * `ACCOUNT_TOKEN_INVALID` is the one shown, and it is a `400` because a dead
     * activation or reset link is an input error: the token is a body parameter
     * proving somebody received an email, not a credential. It answered `401`
     * until that was corrected.
     */
    it('shows a 400 both from the pipe and from a domain rule', () => {
      const codes = examples(400).map(({ value }) => value.errorCode);

      expect(codes).toContain(ERROR_CODES.VALIDATION_ERROR);
      expect(codes).toContain(ERROR_CODES.ACCOUNT_TOKEN_INVALID);
    });

    /**
     * **The property the status correction bought.** `401` on a route with no
     * security requirement now means exactly one thing — the credential in the
     * body was refused — on exactly the two routes where a body carries one.
     */
    it('documents a 401 on no public route but login and refresh', () => {
      const withUnauthorized = operations()
        .filter(
          ({ operation }) =>
            operation.security === undefined &&
            Object.keys(
              operation.responses as Record<string, unknown>,
            ).includes('401'),
        )
        .map(({ method, path }) => `${method} ${path}`);

      expect(withUnauthorized.sort()).toEqual([
        `post ${API_BASE_PATH}/auth/login`,
        `post ${API_BASE_PATH}/auth/refresh`,
      ]);
    });

    /**
     * `409` is mid-migration and the examples say so: most conflicts are still
     * uncoded, one — `ACCOUNT_NOT_PENDING_ACTIVATION` — is not. Showing only the
     * uncoded kind would have taught a client that a `409` never carries a code
     * to branch on, which is the mirror of the `404` mistake.
     */
    it('shows a 409 both with and without a code', () => {
      const codes = examples(409).map(({ value }) => value.errorCode);

      expect(codes).toContain(undefined);
      expect(codes).toContain(ERROR_CODES.ACCOUNT_NOT_PENDING_ACTIVATION);
    });

    /**
     * The array form is what the `ValidationPipe` sends, and a client has to
     * expect it. Only the pipe's variant — a domain rule answering in the `400`
     * shape sends a single string, which is the other half of the pair above.
     */
    it('shows the pipe’s 400 message as the per-field array', () => {
      const fromPipe = examples(400).filter(
        ({ value }) => value.errorCode === ERROR_CODES.VALIDATION_ERROR,
      );

      expect(fromPipe.length).toBeGreaterThan(0);

      for (const { value } of fromPipe) {
        expect(Array.isArray(value.message)).toBe(true);
      }
    });

    /** No example may carry anything resembling a real credential. */
    it('puts no secret in any example', () => {
      const rendered = JSON.stringify(examples().map(({ value }) => value));

      expect(rendered).not.toMatch(/password["']?\s*:/i);
      expect(rendered).not.toMatch(/eyJ[A-Za-z0-9_-]{10,}/);
    });
  });

  // ---------------------------------------------------------------------------
  // The success envelope (Feature 006)
  // ---------------------------------------------------------------------------

  describe('the success envelope', () => {
    /**
     * `ResponseInterceptor` wraps every successful body, so documenting the
     * handler's return type alone would describe a body this API has never
     * sent — the single most likely way for generated documentation to be
     * confidently wrong.
     */
    it('wraps a single object in { success, data }', () => {
      const schema = successSchema(`${API_BASE_PATH}/departments/{id}`, 'get');

      expect(schema.properties?.success).toEqual(
        expect.objectContaining({ enum: [true] }),
      );
      expect(schema.properties?.data).toEqual(
        expect.objectContaining({
          $ref: '#/components/schemas/DepartmentEntity',
        }),
      );
    });

    it('wraps a page in { items, meta }', () => {
      const schema = successSchema(`${API_BASE_PATH}/departments`, 'get');
      const data = schema.properties?.data as {
        properties?: Record<string, { $ref?: string; items?: unknown }>;
      };

      expect(data.properties?.items).toEqual(
        expect.objectContaining({
          items: { $ref: '#/components/schemas/DepartmentEntity' },
        }),
      );
      expect(data.properties?.meta).toEqual({
        $ref: '#/components/schemas/PaginationMeta',
      });
    });

    /** A delete answers `data: null` rather than a 204 with no body. */
    it('documents data: null where the handler returns nothing', () => {
      const schema = successSchema(
        `${API_BASE_PATH}/departments/{id}`,
        'delete',
      );

      expect(schema.properties?.data).toEqual(
        expect.objectContaining({ nullable: true }),
      );
    });

    /**
     * The one endpoint whose response is *not* the envelope, and the
     * documentation has to make the same exception or it would promise JSON on
     * the one route that never sends any.
     */
    it('documents the report export as a binary download', () => {
      const operation = (
        document.paths[
          `${API_BASE_PATH}/reports/{reportType}/export`
        ] as Record<string, Record<string, unknown>>
      ).post;
      const ok = (operation.responses as Record<string, unknown>)['200'] as {
        content?: Record<string, { schema?: { format?: string } }>;
        headers?: Record<string, unknown>;
      };

      expect(Object.keys(ok.content ?? {})).not.toContain('application/json');
      expect(Object.values(ok.content ?? {})[0]?.schema?.format).toBe('binary');
      expect(ok.headers?.['Content-Disposition']).toBeDefined();
    });

    const successSchema = (path: string, method: string) => {
      const operation = (
        document.paths[path] as Record<string, Record<string, unknown>>
      )[method];
      const responses = operation.responses as Record<
        string,
        { content?: Record<string, { schema?: unknown }> }
      >;
      const ok = responses['200'] ?? responses['201'];

      return ok.content?.['application/json']?.schema as {
        properties?: Record<string, unknown>;
      };
    };
  });

  // ---------------------------------------------------------------------------
  // Schemas
  // ---------------------------------------------------------------------------

  describe('the generated schemas', () => {
    /**
     * If the CLI plugin were not running, the schemas would be nearly empty and
     * the secrets assertion below would pass because there was nothing to look
     * at. This is the test that makes that one mean something.
     */
    it('generates properties for request and response classes alike', () => {
      const schemas = document.components?.schemas ?? {};

      expect(Object.keys(schemas).length).toBeGreaterThan(100);

      for (const name of [
        'CreateDepartmentDto',
        'DepartmentEntity',
        'EmployeeEntity',
        'TimesheetEntity',
        'PaginationMeta',
        'ErrorEnvelope',
      ]) {
        const schema = schemas[name] as {
          properties?: Record<string, unknown>;
        };

        expect(Object.keys(schema?.properties ?? {}).length).toBeGreaterThan(1);
      }
    });

    /**
     * The plugin's `introspectComments`, asserted rather than assumed: this
     * project's DTOs already explain why each field exists, and that prose is
     * the documentation. If the option were lost from one of the three places
     * it is configured, this fails.
     */
    it('takes field descriptions from the JSDoc on the property', () => {
      const dto = document.components?.schemas?.CreatePublicHolidayDto as {
        properties?: Record<string, { description?: string }>;
      };

      expect(dto.properties?.type?.description).toContain(
        'the field the rest of the record is judged against',
      );
    });

    /**
     * The constraint hidden inside a composed field decorator, which the plugin
     * cannot see through a function call — the case Feature 038 added an
     * explicit `@ApiProperty` for. Without it the schema would say `string` and
     * nothing else.
     */
    it('publishes the constraints hidden in composed field decorators', () => {
      const dto = document.components?.schemas?.CreateDepartmentDto as {
        properties?: Record<
          string,
          { maxLength?: number; pattern?: string; minLength?: number }
        >;
      };

      expect(dto.properties?.code?.maxLength).toBe(20);
      expect(dto.properties?.code?.pattern).toBeTruthy();
      expect(dto.properties?.name?.maxLength).toBe(100);
      expect(dto.properties?.name?.minLength).toBe(1);
    });

    /** Enums come from the TypeScript type; the plugin resolves them itself. */
    it('publishes enum values', () => {
      const dto = document.components?.schemas?.CreatePublicHolidayDto as {
        properties?: Record<string, { enum?: string[] }>;
      };

      expect(dto.properties?.type?.enum).toEqual(['FIXED', 'VARIABLE']);
    });

    /** Required and nullable are inferred from the declaration, not restated. */
    it('marks optional and nullable fields correctly', () => {
      const dto = document.components?.schemas?.CreateDepartmentDto as {
        required?: string[];
        properties?: Record<string, { nullable?: boolean }>;
      };

      expect(dto.required).toEqual(expect.arrayContaining(['code', 'name']));
      expect(dto.required).not.toContain('description');
      expect(dto.properties?.description?.nullable).toBe(true);
    });
  });

  // ---------------------------------------------------------------------------
  // Secrets
  // ---------------------------------------------------------------------------

  describe('secrets', () => {
    /**
     * **The assertion this feature most needs to be able to make.** The
     * documented schemas are generated from the same classes the mappers
     * populate, and those classes have no field for a hash — so this scans the
     * whole document rather than a list of models, and a schema added next year
     * is covered by it without anybody remembering to add a case.
     */
    it.each([
      'passwordHash',
      'password_hash',
      'tokenHash',
      'token_hash',
      'refreshTokenHash',
    ])('never mentions %s anywhere in the document', (secret) => {
      expect(JSON.stringify(document)).not.toContain(secret);
    });

    /** …and nothing that merely looks like one, under any spelling. */
    it('declares no property whose name contains "hash"', () => {
      const offenders: string[] = [];

      for (const [name, schema] of Object.entries(
        document.components?.schemas ?? {},
      )) {
        const properties =
          (schema as { properties?: Record<string, unknown> }).properties ?? {};

        for (const property of Object.keys(properties)) {
          if (/hash/i.test(property)) {
            offenders.push(`${name}.${property}`);
          }
        }
      }

      expect(offenders).toEqual([]);
    });

    /**
     * The account resource, checked field by field rather than by absence: the
     * documented schema must be exactly what `USER_PUBLIC_SELECT` reads, so a
     * column added to `users` cannot reach the docs without somebody publishing
     * it deliberately.
     */
    it('documents the account resource as exactly the public select', () => {
      const user = document.components?.schemas?.UserEntity as {
        properties?: Record<string, unknown>;
      };

      expect(Object.keys(user.properties ?? {}).sort()).toEqual([
        'createdAt',
        'email',
        'id',
        'role',
        'status',
        'updatedAt',
        'username',
      ]);
    });

    /**
     * The session response *does* carry tokens, and it must — they are the
     * credentials being issued. What it must not carry is a stored hash.
     */
    it('documents the issued tokens but no stored hash', () => {
      const session = document.components?.schemas?.AuthSessionEntity as {
        properties?: Record<string, unknown>;
      };

      expect(Object.keys(session.properties ?? {})).toEqual(
        expect.arrayContaining(['accessToken', 'refreshToken']),
      );
      expect(JSON.stringify(session)).not.toMatch(/hash/i);
    });
  });

  // ---------------------------------------------------------------------------
  // Coexistence with the security headers (Feature 037)
  // ---------------------------------------------------------------------------

  describe('the Content Security Policy', () => {
    /**
     * The scoped relaxation, over HTTP. Feature 037's note said the whole
     * deployment would need `SECURITY_CSP_MODE=relaxed`; this asserts the
     * narrower thing that shipped.
     */
    it('allows inline styles on the documentation page', async () => {
      const response = await request(app.getHttpServer())
        .get(SWAGGER_DOCS_ROUTE)
        .expect(200);

      const policy = response.headers['content-security-policy'];

      expect(policy).toContain("style-src 'self' 'unsafe-inline'");
      expect(policy).toContain("script-src 'self'");
      expect(policy).not.toContain("script-src 'self' 'unsafe-inline'");
      expect(policy).not.toContain('unsafe-eval');
    });

    /** **The point of scoping it.** An API route keeps the strict policy. */
    it('keeps the strict policy on the API', async () => {
      const response = await request(app.getHttpServer())
        .get(`${API_BASE_PATH}/health`)
        .expect(200);

      expect(response.headers['content-security-policy']).toContain(
        "style-src 'self'",
      );
      expect(response.headers['content-security-policy']).not.toContain(
        'unsafe-inline',
      );
    });

    /**
     * `/api/docs-json` does not match the `/api/docs` mount, and that is
     * deliberate rather than incidental: the raw document is JSON and needs no
     * inline anything.
     */
    it('keeps the strict policy on the raw document', async () => {
      const response = await request(app.getHttpServer())
        .get(SWAGGER_JSON_ROUTE)
        .expect(200);

      expect(response.headers['content-security-policy']).not.toContain(
        'unsafe-inline',
      );
    });

    /** Every other security header is still on the documentation page. */
    it('leaves the rest of the header set alone', async () => {
      const response = await request(app.getHttpServer())
        .get(SWAGGER_DOCS_ROUTE)
        .expect(200);

      expect(response.headers['x-content-type-options']).toBe('nosniff');
      expect(response.headers['referrer-policy']).toBe('no-referrer');
      expect(response.headers['x-powered-by']).toBeUndefined();
    });
  });
});

// -----------------------------------------------------------------------------
// The second application: the production default
// -----------------------------------------------------------------------------

/**
 * **Proving the gate in its other state**, which is the only way the default is
 * worth anything. A production deployment that says nothing serves neither
 * route, and the API itself is untouched by their absence.
 */
describe('API documentation, disabled (e2e)', () => {
  let app: INestApplication<App>;

  beforeAll(async () => {
    process.env[SWAGGER_ENABLED_KEY] = 'false';

    app = await bootApplication();
  });

  afterAll(async () => {
    delete process.env[SWAGGER_ENABLED_KEY];
    await app.close();
  });

  it('does not serve the UI', () =>
    request(app.getHttpServer()).get(SWAGGER_DOCS_ROUTE).expect(404));

  it('does not serve the raw document', () =>
    request(app.getHttpServer()).get(SWAGGER_JSON_ROUTE).expect(404));

  it('does not serve the UI assets', () =>
    request(app.getHttpServer())
      .get(`${SWAGGER_DOCS_ROUTE}/swagger-ui-bundle.js`)
      .expect(404));

  /**
   * The 404 is the ordinary Feature 033 envelope from `AllExceptionsFilter`,
   * not a bare Express page — which is what proves the route genuinely does not
   * exist rather than being served and refused.
   */
  it('renders the refusal as the standard error envelope', async () => {
    const response = await request(app.getHttpServer())
      .get(SWAGGER_DOCS_ROUTE)
      .expect(404);

    expect(response.body).toEqual({
      success: false,
      statusCode: 404,
      message: expect.any(String) as unknown as string,
      path: SWAGGER_DOCS_ROUTE,
      timestamp: expect.any(String) as unknown as string,
    });
  });

  /** The application is otherwise exactly the application. */
  it('serves the API unchanged', () =>
    request(app.getHttpServer())
      .get(`${API_BASE_PATH}/health`)
      .expect(200)
      .expect({ success: true, data: { status: 'ok', service: 'backend' } }));

  /** And with the strict policy, since nothing relaxed it. */
  it('serves the strict policy everywhere', async () => {
    const response = await request(app.getHttpServer())
      .get(`${API_BASE_PATH}/health`)
      .expect(200);

    expect(response.headers['content-security-policy']).not.toContain(
      'unsafe-inline',
    );
  });
});
