import { INestApplication } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DocumentBuilder, OpenAPIObject, SwaggerModule } from '@nestjs/swagger';
import helmet from 'helmet';

import { API_BASE_PATH, API_DEFAULT_VERSION } from './api.constants';
import { buildDocsCspOptions } from './helmet.config';
import { API_TAGS } from './swagger-tags';
import {
  SWAGGER_DOCS_PATH,
  SWAGGER_DOCS_ROUTE,
  isSwaggerEnabled,
} from './swagger.config';

/**
 * Name of the security scheme the "Authorize" button fills in.
 *
 * Referenced by symbol from `@ApiBearerAuth()` on every controller, so the
 * button and the padlocks are wired to one another by the compiler rather than
 * by two matching strings.
 */
export const BEARER_AUTH_NAME = 'access-token';

const TITLE = 'CRM TimeSheet API';

/**
 * The page a consumer reads before any endpoint.
 *
 * It states the four things that are true of *every* route and that a
 * per-endpoint description would have to repeat 150 times: the envelope, the
 * token, the limits, and how time is represented.
 */
const DESCRIPTION = `
Timesheets, leave and the people behind them.

### Base path

Every endpoint below is served under \`${API_BASE_PATH}\`. The version is part of
the URL, so a future controller can move to \`/v2\` while everything else keeps
answering here.

### The response envelope

**Every** successful response is \`{ "success": true, "data": … }\` and every
failure is the \`ErrorEnvelope\` schema. \`success\` is the discriminant: a client
reads one field to know which it received, without inspecting the status code
first. The two shapes are produced in exactly two places — a global interceptor
and a global exception filter — so no endpoint can forget one.

The one exception is a report export, which returns a spreadsheet or a PDF.
There is no reading of \`{ success, data }\` that can contain a binary file.

### Authentication

Every route requires \`Authorization: Bearer <access token>\` unless it is marked
otherwise — a global guard makes that the default, so a route added tomorrow is
protected because nobody did anything. Obtain a token from
\`POST ${API_BASE_PATH}/auth/login\`, then use **Authorize** above to send it with
every request on this page.

The routes without a padlock are not unprotected; each is protected by a
different credential — a password, a refresh token, or the secret in an emailed
link.

### Errors

Beside the HTTP status, a failure may carry a stable \`errorCode\`
(\`AUTH_INVALID_CREDENTIALS\`, \`VALIDATION_ERROR\`) plus \`params\`. Branch on the
code, never on the English \`message\`, which is written for a log and is free to
be reworded. The code being *absent* is part of the contract too: modules
written before error codes existed still answer without one, so fall back to
\`statusCode\`.

### Rate limits

Every route is limited per client, with a much stricter allowance on the public
authentication routes. A refusal is a \`429\` carrying \`Retry-After\` in seconds —
retrying sooner extends the block rather than shortening it.

### Dates

Every timestamp this API **sends** is ISO-8601 UTC. Formatting is the client's
job, and it should render in the company timezone from
\`GET ${API_BASE_PATH}/work-schedule\` rather than in the browser's — these are
shared business facts, and a screen that disagrees with the PDF exported from it
is a bug.

Every date this API **accepts** is ISO-8601 too, and both spellings are valid:
a calendar date (\`2026-09-01\`) or a full instant (\`2026-09-01T00:00:00.000Z\`).
Date fields are documented as plain strings for that reason — \`format:
date-time\` would describe only the second and a generated client validating on
it would reject requests this API accepts.
`.trim();

/**
 * Serves the API documentation, if this deployment is configured to.
 *
 * ## Where it runs, and why after `configureApp`
 *
 * `main.ts` calls this immediately after `configureApp(app)` and before
 * `app.listen`, and both halves of that matter.
 *
 * **After**, because the document is generated by inspecting the application
 * that `configureApp` has finished configuring. `setGlobalPrefix` and
 * `enableVersioning` are what turn a controller's `@Controller('departments')`
 * into `${API_BASE_PATH}/departments`, and the scanner reads both from the
 * application — so the paths in the document are the real ones and "Try it out"
 * hits the route the reader is looking at. Generated before, every path would
 * be missing `/api/v1` and every request from the page would 404.
 *
 * **Not inside `configureApp`**, unlike every other global concern, and that is
 * deliberate rather than an oversight. That function is the contract the e2e
 * suite boots through, and it must keep describing the *application* — the
 * prefix, the pipe, the envelope, the guards. Documentation is a property of
 * the deployment: it is optional, it is env-gated, and a spec that wanted to
 * assert the application's behaviour with the documentation switched off could
 * not do so if generating it were unconditional. `openapi.e2e-spec.ts` calls
 * `configureApp` and then this function, exactly as `main.ts` does.
 *
 * ## What is served
 *
 * - `${SWAGGER_DOCS_ROUTE}` — the interactive UI.
 * - `${SWAGGER_DOCS_ROUTE}-json` — the raw OpenAPI document, which is the
 *   contract the frontend reads and can generate a typed client from.
 *
 * Both are registered straight onto the Express adapter by `SwaggerModule`,
 * which means they are outside Nest's routing pipeline entirely: no global
 * prefix, no versioning, no guards, no `ValidationPipe`, no response envelope.
 * The documentation is therefore reachable without an access token when it is
 * enabled — it has to be, since it is what tells a caller how to obtain one —
 * and `@Public()` is not involved, because there is no Nest route for a guard
 * to have exempted. Whether it is reachable *at all* is
 * {@link isSwaggerEnabled}.
 *
 * @returns whether the documentation was mounted, so bootstrap can log the URL.
 */
export function setupSwagger(app: INestApplication): boolean {
  const configService = app.get(ConfigService);

  if (!isSwaggerEnabled(configService)) {
    return false;
  }

  // The scoped CSP relaxation (Feature 037's note, honoured narrowly). Helmet
  // has already run globally inside `configureApp` and written the strict
  // policy onto every response; this middleware is mounted at the docs path
  // only and overwrites that one header for the one page that renders HTML.
  // Mounting by path is what keeps the blast radius to the documentation:
  // `/api/docs-json` does not match the mount, so the raw document — which is
  // JSON and needs no inline anything — keeps the strict policy too.
  app.use(
    SWAGGER_DOCS_ROUTE,
    helmet.contentSecurityPolicy(buildDocsCspOptions(configService)),
  );

  SwaggerModule.setup(SWAGGER_DOCS_PATH, app, buildDocument(app), {
    // Keeps the token across a page reload, so a reader who authorised once is
    // not asked again every time they follow a deep link into a section.
    swaggerOptions: { persistAuthorization: true },
    customSiteTitle: TITLE,
  });

  return true;
}

/**
 * Builds the OpenAPI document from the running application.
 *
 * Exported so a test can assert on the document without starting a server, and
 * so it can be generated with the UI switched off.
 */
export function buildDocument(app: INestApplication): OpenAPIObject {
  const config = new DocumentBuilder()
    .setTitle(TITLE)
    .setDescription(DESCRIPTION)
    // The version of the API this document describes, which is the URI version
    // rather than the npm package version of the backend. A consumer cares
    // that this is the contract of `/v1`; the build number of the process
    // serving it is not something they can act on, and tying the two would
    // change the document's advertised version on every unrelated release.
    .setVersion(API_DEFAULT_VERSION)
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description:
          'The `accessToken` from `POST /auth/login` or `POST /auth/refresh`. Short-lived by design — 15 minutes by default — so expect to refresh it. Paste the token alone; the `Bearer ` prefix is added for you.',
      },
      BEARER_AUTH_NAME,
    );

  // No `.addServer()`. The scanner already writes the global prefix and the
  // URI version into every path, so a server entry of `/api/v1` would be
  // prepended to a path that already carries it and every "Try it out" request
  // would go to `/api/v1/api/v1/…`. The document's paths are absolute against
  // the origin the page was served from, which is what makes them correct
  // behind a proxy as well as locally.

  // Declared in reading order, which is the order Swagger UI renders the
  // groups in. See `swagger-tags.ts` for why it is not alphabetical.
  for (const tag of API_TAGS) {
    config.addTag(tag.name, tag.description);
  }

  return SwaggerModule.createDocument(app, config.build());
}
